# Generated by Django 4.2.4 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SkinAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("image", models.ImageField(upload_to="skin_images/")),
                ("diagnosis", models.CharField(blank=True, max_length=255)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Skin Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
