class IntentConstants:
    USER_INTENT_GREETING = "Greeting"
    USER_INTENT_DISAPPOINTMENT = "Disappointment"
    USER_INTENT_HEALTH = "Health_related"
    USER_INTENT_REFERRING_BACK = "Referring_back"
    USER_INTENT_CHANGE_TOPIC = "Change_topic"
    USER_INTENT_UNCLEAR = "Unclear"
    USER_INTENT_EXIT = "Exit"
    USER_INTENT_OUT_CONTEXT = "Out_of_context"
    USER_INTENT_MEDICAL_EMERGENCY = "Medical_Emergency"
