# Generated by Django 4.1.5 on 2025-12-02 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalKnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("content", models.TextField()),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("who", "WHO Guidelines"),
                            ("pubmed", "PubMed Research"),
                            ("fda", "FDA Information"),
                            ("cdc", "CDC Updates"),
                            ("manual", "Manual Entry"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("qdrant_id", models.CharField(blank=True, max_length=100)),
                ("ingested_via_kafka", models.BooleanField(default=False)),
                ("kafka_topic", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "medical_knowledge_base",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMedicalProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medical_conditions", models.JSONField(blank=True, default=list)),
                ("current_medications", models.JSONField(blank=True, default=list)),
                ("allergies", models.JSONField(blank=True, default=list)),
                (
                    "age_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("child", "Child (0-12)"),
                            ("teen", "Teen (13-17)"),
                            ("adult", "Adult (18-64)"),
                            ("senior", "Senior (65+)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("dietary_restrictions", models.JSONField(blank=True, default=list)),
                ("pregnancy_status", models.BooleanField(default=False)),
                ("is_profile_complete", models.BooleanField(default=False)),
                (
                    "onboarding_completed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_medical_profiles",
            },
        ),
        migrations.CreateModel(
            name="MedicalImageAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="medical_images/%Y/%m/%d/")),
                ("analysis_result", models.JSONField(blank=True, null=True)),
                ("detected_conditions", models.JSONField(blank=True, default=list)),
                ("suggested_remedies", models.JSONField(blank=True, default=list)),
                ("requires_medical_attention", models.BooleanField(default=False)),
                (
                    "severity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High - Seek Medical Help"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "medical_image_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabReportAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_file", models.FileField(upload_to="lab_reports/%Y/%m/%d/")),
                (
                    "report_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("cbc", "Complete Blood Count"),
                            ("metabolic", "Metabolic Panel"),
                            ("lipid", "Lipid Panel"),
                            ("thyroid", "Thyroid Function"),
                            ("liver", "Liver Function"),
                            ("kidney", "Kidney Function"),
                            ("general", "General Lab Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("analysis_result", models.JSONField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("abnormal_findings", models.JSONField(blank=True, default=list)),
                (
                    "personalized_recommendations",
                    models.JSONField(blank=True, default=list),
                ),
                ("requires_doctor_consultation", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lab_report_analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("image_url", models.URLField(blank=True, null=True)),
                ("tokens_used", models.IntegerField(default=0)),
                ("model_used", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="servvia.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
    ]
