# Generated by Django 4.2.4 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_id", models.EmailField(max_length=254)),
                ("report_file", models.FileField(upload_to="lab_reports/")),
                ("extracted_text", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("analysis", models.JSONField(blank=True, default=dict)),
                ("abnormal_values", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
